---
# Operaciones sobre todos los nodos
- hosts: all

  gather_facts: false
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: sudo

  # Desactivar ejecución en paralelo para evitar problemas con Vagrant-Cachier
  serial: 1

  vars:
    equipo: "{{ inventory_hostname }}"

  vars_files:
    - vars/main.yml


  tasks:

    - name: Configurar display_errors = on
      ini_file: dest=/etc/php/7.0/apache2/php.ini section=PHP
         option=display_errors
         value=On
      notify: restart apache
      tags:
        - enable

    - name: Configurar display_errors = off
      ini_file: dest=/etc/php/7.0/apache2/php.ini section=PHP
         option=display_errors
         value=Off
      notify: restart apache
      tags:
        - disable


  handlers:
    - import_tasks: handlers/main.yml

