---
# Operaciones sobre todos los nodos
- hosts: all

  gather_facts: true
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: sudo

  # Desactivar ejecución en paralelo para evitar problemas con Vagrant-Cachier
  serial: 1

  vars:
    equipo: "{{ inventory_hostname }}"

  vars_files:
    - vars/main.yml


  tasks:
    # Base de datos
    - name: Enviar volcado de la base de datos configurado
      copy: src=files/backup/moodle_db.sql
        dest=/tmp/moodle_db.sql
        owner={{ moodle_dir_owner }} group={{ moodle_dir_group }} mode={{ moodle_dir_permissions_files }}

    - name: Importar Base de Datos
      mysql_db: name={{ db_name }} state=import target=/tmp/moodle_db.sql


    # Directorio moodledata
    - name: Limpiar directorio moodledata
      file: path={{ moodle_data }}
        state=absent

    - name: Crear directorio de datos
      file: path={{ moodle_data }}
        state=directory recurse=yes
        owner={{ moodle_data_owner }} group={{ moodle_data_group }} mode={{ moodle_data_permissions_dirs }}

    - name: Importar directorio moodledata
      unarchive: src=files/backup/moodledata.tar.gz
        dest={{ moodle_data }}/..
        owner={{ moodle_data_owner }} group={{ moodle_data_group }} mode={{ moodle_data_permissions_dirs }}

    - name: Configurar permisos de moodledata
      command: find {{ moodle_data }} -type f -exec chmod {{ moodle_data_permissions_files }} {} \;


    # Archivo config.php
    - name: Configurar archivo config.php
      copy: src=files/backup/config.php
        dest={{ moodle_dir }}/config.php
        owner={{ moodle_dir_owner }} group={{ moodle_dir_group }} mode={{ moodle_dir_permissions_files }}


  handlers:
    - include: handlers/main.yml

