---

# Operaciones comunes sobre todos los nodos
- import_playbook: common.yml

# Instalación de Apache/PHP/MySQL
- import_playbook: lamp.yml

# Desplegar archivos de aplicación y preparar base de datos
- import_playbook: moodle-install.yml

# Restaurar copia de seguridad
#- import_playbook: moodle-restore.yml

