---
# MySQL modules
- name: Instalar MySQL
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server
    - python-mysqldb
  notify: start mysql

- name: Configurar ajustes de MySQL
  template: src=etc/mysqld.cnf.j2
    dest=/etc/mysql/mysql.conf.d/mysqld.cnf
    owner=root group=root mode=0644
  notify: restart mysql

