---
# Instalación de PHP
- name: Instalar PHP
  apt: pkg={{ item }} state=present update_cache=yes
  with_items: "{{ php_packages }}"
  notify: restart apache

- name: Instalar módulos de PHP
  apt: pkg={{ item }} state=present update_cache=yes
  with_items: "{{ php_modules }}"
  notify: restart apache

- name: Configurar parámetros de PHP
  ini_file: dest={{ php_ini_file }} section=PHP
     option={{ item.param }}
     value={{ item.value }}
  with_items: "{{ php_settings }}"
  notify: restart apache

